// CommonJS, every file is module (by default)
//  Modules - Encapsulated Code (only share minimum)
const names = require('./4-names')
const sayHi = require('./5-utils')
const items = require('./6-alternative-flavor')
require('./7-mind-grenade')
// console.log(items)

// sayHi('susan')
// sayHi(names.john)
// sayHi(names.peter)
// sayHi(items.items[0])
// sayHi(items.items[1])
// sayHi(items.singlePerson['name'])